from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
    url(r'^register/$', views.UserRegistrationAPIView.as_view(), name='register'),
    url(r'^edit_user/$', views.edit_user, name='edit_user'),
    url(r'^edit_school/$', views.edit_school, name='edit_school'),
    url(r'^all_users/$', views.Users.as_view(), name='all_users'),
    url(r'^user/$', views.User.as_view(), name='all_users'),
    url(r'^login/$', views.UserLoginAPIView.as_view(), name='login'),
    url(r'^new_school/$', views.SchoolRegistrationAPIView.as_view(), name='new_school'),
    url(r'^mobile_login/$', csrf_exempt(views.MobileLoginAPIView.as_view()), name='mobile_login'),
    url(r'^visited_school/$', views.VisitedSchoolList.as_view(), name='visited_school'),
    url(r'^hypo_data/$', views.HypoCreationAPIView.as_view(), name='hypo_data'),
    url(r'^hypo_data02/$', views.HypoCreationAPIView02.as_view(), name='hypo_data02'),
    url(r'^user_modules/$', views.ModulesList.as_view(), name='user_modules'),
    url(r'^hypo/$', views.HypoData.as_view(), name='hypo'),
    url(r'^update_school/(?P<pk>\d+)/$', views.SchoolUpdateAPIView.as_view(), name='update_school'),
    url(r'^update_school2/(?P<pk>\d+)/$', views.SchoolUpdateAPIView2.as_view(), name='update_school2'),
    url(r'^new_apt/$', views.SchoolAppointmentAPIView.as_view(), name='new_appointment'),
    url(r'^sop/$', views.SchoolRatingAPIView.as_view(), name='sop'),
    url(r'^schools/$', views.SchoolList.as_view(), name='schools'),
    url(r'^approve/$', views.approve_school, name='approve schools'),
    url(r'^delete/$', views.del_school, name='delete schools'),
    url(r'^report_data/$', views.managers_reports, name='tt'),
    url(r'^supervisor_data/$', views.supervisor_reports, name='form data'),
    url(r'^feedback_data/$', views.form_reports, name='supervisor data'),
    url(r'^report/$', views.managers_excel, name='mex'),
    url(r'^supervisor_excel/$', views.supervisor_excel, name='s_ex'),
    url(r'^school_excel/$', views.schools_excel, name='ss_ex'),
    url(r'^feedback_excel/$', views.feedback_excel, name='fb_ex'),
    url(r'^last_school_date/$', views.last_date, name='lst'),
    url(r'^last_hypo_date/$', views.hypo_last_date),
    url(r'^hypo_update/(?P<app_uuid>.*)/$', views.HypoUpdateAPIView.as_view(), name='hypo_update'),
    url(r'^hypo_numbers/$', views.hypo_numbers, name='hypo numbers'),
    url(r'^hypo_summary/$', views.hypo_summary),
    url(r'^summary_excel/$', views.summary_excel),
    url(r'^hypo_lga_report/$', views.hypo_lga_report),
    url(r'^hypo_lga_excel/$', views.hypo_lga_excel),
    url(r'^hypo_excel/$', views.hypo_excel),
    url(r'^new_hotel/$', views.NewHotel.as_view()),
    url(r'^new_restaurant/$', views.NewRestaurant.as_view()),
    url(r'^new_bar/$', views.NewBar.as_view()),
    url(r'^new_cafe/$', views.NewCafe.as_view()),
    url(r'^hotels/$', views.HotelData.as_view()),
    url(r'^restaurants/$', views.RestaurantData.as_view()),
    url(r'^bars/$', views.BarData.as_view()),
    url(r'^cafes/$', views.CafeData.as_view()),
    url(r'^hotel_update/(?P<app_uid>.*)/$', views.HotelUpdateAPIView.as_view()),
    url(r'^restaurant_update/(?P<app_uid>.*)/$', views.RestaurantUpdateAPIView.as_view()),
    url(r'^bar_update/(?P<app_uid>.*)/$', views.BarUpdateAPIView.as_view()),
    url(r'^cafe_update/(?P<app_uid>.*)/$', views.CafeUpdateAPIView.as_view()),
    url(r'^hotel_excel/$', views.hotel_excel),
    url(r'^restaurant_excel/$', views.restaurant_excel),
    url(r'^bar_excel/$', views.bar_excel),
    url(r'^cafe_excel/$', views.cafe_excel),
    url(r'^k_retail/$', views.KelloggsRetailAPIView.as_view()),
    url(r'^k_pre/$', views.KelloggsPreSamplingAPIView.as_view()),
    url(r'^k_post/$', views.KelloggsPostSamplingAPIView.as_view()),
    url(r'^k_retail_excel/$', views.k_retail_excel),
    url(r'^k_pre_excel/$', views.k_pre_excel),
    url(r'^k_post_excel/$', views.k_post_excel),
    url(r'^k_school/$', views.KelloggsSchoolSamplingAPIView.as_view()),
    url(r'^k_school_update/(?P<app_uid>.*)/$', views.KelloggsSchoolUpdateAPIView.as_view()),
    url(r'^k_visited/$', views.KVisitedSchoolsAPIView.as_view()),
    url(r'^k_school_excel/$', views.kelloggs_schools_excel),
    url(r'^first_date/$', views.first_date),
    url(r'^k_summary/$', views.kelloggs_summary),
    url(r'^k_managers_report/$', views.k_managers_reports),
    url(r'^k_supervisor_report/$', views.k_supervisor_reports),
    url(r'^k_summary_export/$', views.k_feedback_excel),
    url(r'^k_manager_export/$', views.k_managers_excel),
    url(r'^k_supervisor_export/$', views.k_supervisor_excel),
    url(r'^countries/$', views.CountryAPIView.as_view()),
    url(r'^new_country/$', views.CountryCreateAPIView.as_view()),
    url(r'^hotels2/$', views.HotelList.as_view()),
    url(r'^restaurants2/$', views.RestaurantLite.as_view()),
    url(r'^bars2/$', views.BarLite.as_view()),
    url(r'^cafes2/$', views.CafeLite.as_view()),
    url(r'^school_numbers/$', views.school_numbers),
    url(r'^get_users/$', views.Users02.as_view()),
    url(r'^users_export/$', views.users_excel),
    url(r'^sch_admin_update/(?P<pk>\d+)/$', views.SchoolUpdateAPIViewAdmin.as_view()),
    ]