# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imei',
            field=models.CharField(blank=True, max_length=50, verbose_name='IMEI'),
        ),
    ]
