# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0002_auto_20180920_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hypo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Hypo Sampling'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-id'], 'verbose_name_plural': 'School Sampling'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='hypo',
            name='app_uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App UUID'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='prd_1',
            field=models.ImageField(blank=True, default='hypo/images/noimage.jpg', null=True, upload_to='hypo/images/', verbose_name='Product Demo 1'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='prd_2',
            field=models.ImageField(blank=True, default='hypo/images/noimage.jpg', null=True, upload_to='hypo/images/', verbose_name='Product Demo 2'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='prd_3',
            field=models.ImageField(blank=True, default='hypo/images/noimage.jpg', null=True, upload_to='hypo/images/', verbose_name='Product Demo 3'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='prd_4',
            field=models.ImageField(blank=True, default='hypo/images/noimage.jpg', null=True, upload_to='hypo/images/', verbose_name='Product Demo 4'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='prd_5',
            field=models.ImageField(blank=True, default='hypo/images/noimage.jpg', null=True, upload_to='hypo/images/', verbose_name='Product Demo 5'),
        ),
        migrations.AddField(
            model_name='school',
            name='target_level',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Nursery & Primary', 'Nursery & Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary'), ('Junior & Senior Secondary', 'Junior & Senior Secondary'), ('Creche', 'Creche'), ('Kindergarten', 'Kindergarten')], max_length=100, null=True, verbose_name='Target Level'),
        ),
        migrations.AddField(
            model_name='school',
            name='target_population',
            field=models.IntegerField(default=0, verbose_name='Target Population'),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Nursery - Primary', 'Nursery - Primary'), ('Nursery - Secondary', 'Nursery - Secondary'), ('Primary - Secondary', 'Primary - Secondary'), ('Secondary School', 'Secondary School'), ('Creche/Nursery/Primary/Secondary', 'Creche/Nursery/Primary/Secondary')], max_length=100, verbose_name='Level'),
        ),
    ]
