# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_auto_20180926_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypo',
            name='demo_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='Demo Given'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='fb_liked',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='Facebook Page Liked'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='hypo_seen',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='Hypo Seen'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='sampled',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='Sampled Before'),
        ),

    ]
