# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0004_auto_20180926_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypo',
            name='duplicate',
            field=models.BooleanField(default=False, verbose_name='Duplicate'),
        ),
        migrations.AddField(
            model_name='hypo',
            name='duplicate_uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Duplicate UUID'),
        ),
        migrations.AlterField(
            model_name='hypo',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
    ]
