# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-08 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0005_auto_20181030_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact Phone Number')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Designation')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dance Floor', 'Dance Floor'), ('Recreational Area', 'Recreational Area'), ('Pool Side', 'Pool Side')], max_length=100, null=True, verbose_name='Amenities')),
                ('sample_type', models.CharField(blank=True, choices=[('Night Club', 'Night Club'), ('Lounge', 'Lounge'), ('Beer Parlor', 'Beer Parlor')], max_length=100, null=True, verbose_name='Type')),
                ('food_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dance Floor', 'Dance Floor'), ('Recreational Area', 'Recreational Area'), ('Pool Side', 'Pool Side')], max_length=100, null=True, verbose_name='Food Type')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Bars/Pubs/Night Clubs',
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact Phone Number')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Designation')),
                ('offering', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bread', 'Bread'), ('Pastries', 'Pastries'), ('Cakes', 'Cakes'), ('Ice Cream', 'Ice Cream'), ('Coffee', 'Coffee'), ('Beverages', 'Beverages'), ('Finger Food', 'Finger Food')], max_length=100, null=True, verbose_name='Food Offering')),
                ('sample_type', models.CharField(blank=True, choices=[('Take Away', 'Take Away'), ('Eat In', 'Eat In')], max_length=100, null=True, verbose_name='Type')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Banquet', 'Banquet'), ('Bar', 'Bar'), ('Kids play area', 'Kids play area')], max_length=100, null=True, verbose_name='Amenities')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Bakery/Confectionery/Cafe',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact Phone Number')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Designation')),
                ('no_of_rooms', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Rooms')),
                ('no_of_restaurants', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Restaurants/Cafeteria')),
                ('restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
                ('bar', models.BooleanField(default=False, verbose_name='Bar')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('spa', models.BooleanField(default=False, verbose_name='Spa')),
                ('casino', models.BooleanField(default=False, verbose_name='Casino')),
                ('salon', models.BooleanField(default=False, verbose_name='Salon')),
                ('boutiques', models.BooleanField(default=False, verbose_name='Boutiques')),
                ('elevator', models.BooleanField(default=False, verbose_name='Elevator')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('concierge', models.BooleanField(default=False, verbose_name='Concierge')),
                ('recreation_room', models.BooleanField(default=False, verbose_name='Recreation Room')),
                ('night_club', models.BooleanField(default=False, verbose_name='Night Clud')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact Phone Number')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Designation')),
                ('no_of_tables', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Tables')),
                ('no_of_waiting_staff', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Waiting Staff')),
                ('cuisines', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nigerian', 'Nigerian'), ('Chinese', 'Chinese'), ('Continental', 'Continental'), ('Indian', 'Indian'), ('Arabic/Lebanese', 'Arabic/Lebanese'), ('Mexican', 'Mexican'), ('Italian', 'Italian'), ('Asian', 'Asian')], max_length=100, null=True, verbose_name='Cuisines')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Banquet', 'Banquet'), ('Bar', 'Bar'), ('Kids play area', 'Kids play area')], max_length=100, null=True, verbose_name='Amenities')),
                ('sample_type', models.CharField(blank=True, choices=[('Fine Dine', 'Fine Dine'), ('Cafe', 'Cafe'), ('Casual', 'Casual'), ('Fast Food', 'Fast Food'), ('Buka', 'Buka'), ('Canteen', 'Canteen')], max_length=100, null=True, verbose_name='Type')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Restaurant / Cafeteria',
            },
        ),
    ]
