# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0006_auto_20181208_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='boutiques',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='casino',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='concierge',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='night_club',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='recreation_room',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='spa',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='swimming_pool',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='wifi',
        ),
    ]
