# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-08 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0007_auto_20181208_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Swimming Pool', 'Swimming Pool'), ('Gym', 'Gym'), ('Spa', 'Spa'), ('Casino', 'Casino'), ('Salon', 'Salon'), ('Boutiques', 'Boutiques'), ('Elevator', 'Elevator'), ('Wifi', 'Wifi'), ('Concierge', 'Concierge'), ('Recreation Room', 'Recreation Room'), ('Night Club', 'Night Club')], max_length=100, null=True, verbose_name='Amenities'),
        ),
    ]
