# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0009_auto_20181209_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='no_of_tables',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Tables'),
        ),
        migrations.AddField(
            model_name='bar',
            name='no_of_waiting_staff',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Waiting Staff'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='no_of_tables',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Tables'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='no_of_waiting_staff',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Waiting Staff'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='showroom',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Showroom'),
        ),
    ]
