# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0011_auto_20181209_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='bar',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='food_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nigerian', 'Nigerian'), ('Fast Food', 'Fast Food'), ('Continental', 'Continental')], max_length=100, null=True, verbose_name='Food Type'),
        ),
    ]
