# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0012_auto_20181209_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='bar',
            name='app_uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App UID'),
        ),
        migrations.AddField(
            model_name='bar',
            name='image_1',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='bar',
            name='image_2',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='bar',
            name='image_3',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='bar',
            name='image_4',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='bar',
            name='image_5',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='app_uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App UID'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='image_1',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='image_2',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='image_3',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='image_4',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='image_5',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='app_uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App UID'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_1',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_2',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_3',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_4',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_5',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='app_uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App UID'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_1',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_2',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_3',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_4',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_5',
            field=models.ImageField(blank=True, default='horeca/images/noimage.jpg', upload_to='horeca/images/', verbose_name='Image 5'),
        ),

    ]
