# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0013_auto_20181210_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),

    ]
