# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0014_auto_20181212_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='captured_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Captured'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='captured_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Captured'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='captured_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Captured'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='captured_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Captured'),
        ),

    ]
