# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0016_auto_20190116_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelloggsPostSampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='LGA')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('knows_kelloggs', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Knows Kelloggs')),
                ('knows_coco_pops', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Knows Kelloggs Coco Pops')),
                ('coco_pops_sachet_seen', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Coco Pops Sachet Seen')),
                ('known_from', models.TextField(blank=True, max_length=700, null=True, verbose_name='Known From')),
                ('eats_coco_pops', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Consumes Kelloggs Coco Pops')),
                ('consumption_rate', models.CharField(blank=True, max_length=120, null=True, verbose_name='Comsumption Rate')),
                ('consumption_style', models.TextField(blank=True, max_length=700, null=True, verbose_name='Consumption Style')),
                ('consumption_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Consumption Time')),
                ('as_kids_breakfast', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Given to Kids as Breakfast')),
                ('preferred_as_kids_breakfast', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Preferred as Kids Breakfast')),
                ('preferred_kids_breakfast', models.CharField(blank=True, max_length=600, null=True, verbose_name='Preferred Kids Breakfast')),
                ('preferred_adult_breakfast', models.CharField(blank=True, max_length=600, null=True, verbose_name='Preferred Adult Breakfast')),
                ('kids_requested', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Kids Requested Coco Pos for Breakfast')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Kelloggs Post Sampling',
            },
        ),
        migrations.CreateModel(
            name='KelloggsPreSampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='LGA')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('knows_kelloggs', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Knows Kelloggs')),
                ('knows_coco_pops', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Knows Kelloggs Coco Pops')),
                ('coco_pops_sachet_seen', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Coco Pops Sachet Seen')),
                ('eats_coco_pops', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Consumes Kelloggs Coco Pops')),
                ('consumption_rate', models.CharField(blank=True, max_length=120, null=True, verbose_name='Comsumption Rate')),
                ('consumption_style', models.TextField(blank=True, max_length=700, null=True, verbose_name='Consumption Style')),
                ('consumption_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Consumption Time')),
                ('as_kids_breakfast', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Given to Kids as Breakfast')),
                ('preferred_as_kids_breakfast', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Preferred as Kids Breakfast')),
                ('preferred_kids_breakfast', models.CharField(blank=True, max_length=600, null=True, verbose_name='Preferred Kids Breakfast')),
                ('preferred_adult_breakfast', models.CharField(blank=True, max_length=600, null=True, verbose_name='Preferred Adult Breakfast')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Kelloggs Pre Sampling',
            },
        ),
        migrations.CreateModel(
            name='KelloggsRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Outlet')),
                ('lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='LGA')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('kelloggs_available', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Kellogg Available')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU')),
                ('knows_kelloggs', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Do You Know Kelloggs')),
                ('knows_coco_pops', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Do You Know Kelloggs Coco Pops')),
                ('carton_sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='Weekly Carton Sales')),
                ('consumes_at_home', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Consumes Kelloggs At Home')),
                ('sachet_selling_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Selling Price Per Sachet')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Kelloggs Retail',
            },
        ),
    ]
