# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0017_auto_20190127_2253'),
    ]

    operations = [

        migrations.AddField(
            model_name='kelloggspostsampling',
            name='date_captured',
            field=models.DateField(blank=True, null=True, verbose_name='Date Captured'),
        ),
        migrations.AddField(
            model_name='kelloggspresampling',
            name='date_captured',
            field=models.DateField(blank=True, null=True, verbose_name='Date Captured'),
        ),
        migrations.AddField(
            model_name='kelloggsretail',
            name='date_captured',
            field=models.DateField(blank=True, null=True, verbose_name='Date Captured'),
        ),

    ]
