# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0018_auto_20190130_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelloggspostsampling',
            name='branch',
            field=models.CharField(blank=True, choices=[('Central', 'Central'), ('East 1', 'East 1'), ('East 2', 'East 2'), ('East 3', 'East 3'), ('East 4', 'East 4'), ('East 5', 'East 5'), ('East 6', 'East 6'), ('Lagos 1', 'Lagos 1'), ('Lagos 2', 'Lagos 2'), ('North 1', 'North 1'), ('North 2', 'North 2'), ('North 3', 'North 3'), ('South Central', 'South Central'), ('South West', 'South West')], max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='kelloggspostsampling',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='kelloggspostsampling',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='kelloggspresampling',
            name='branch',
            field=models.CharField(blank=True, choices=[('Central', 'Central'), ('East 1', 'East 1'), ('East 2', 'East 2'), ('East 3', 'East 3'), ('East 4', 'East 4'), ('East 5', 'East 5'), ('East 6', 'East 6'), ('Lagos 1', 'Lagos 1'), ('Lagos 2', 'Lagos 2'), ('North 1', 'North 1'), ('North 2', 'North 2'), ('North 3', 'North 3'), ('South Central', 'South Central'), ('South West', 'South West')], max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='kelloggspresampling',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='kelloggspresampling',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='kelloggsretail',
            name='branch',
            field=models.CharField(blank=True, choices=[('Central', 'Central'), ('East 1', 'East 1'), ('East 2', 'East 2'), ('East 3', 'East 3'), ('East 4', 'East 4'), ('East 5', 'East 5'), ('East 6', 'East 6'), ('Lagos 1', 'Lagos 1'), ('Lagos 2', 'Lagos 2'), ('North 1', 'North 1'), ('North 2', 'North 2'), ('North 3', 'North 3'), ('South Central', 'South Central'), ('South West', 'South West')], max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='kelloggsretail',
            name='lat',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='kelloggsretail',
            name='lng',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='kelloggsretail',
            name='sampling_type',
            field=models.CharField(blank=True, choices=[('Post_Sampling', 'Post_Sampling'), ('Pre_Sampling', 'Pre_Sampling')], max_length=100, null=True, verbose_name='Sampling Type'),
        ),
    ]
