# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-27 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0019_auto_20190205_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelloggsSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='School Name')),
                ('school_type', models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=100, null=True, verbose_name='School Type')),
                ('visited', models.BooleanField(default=False, verbose_name='Visited')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('landmark', models.CharField(blank=True, max_length=200, null=True, verbose_name='Landmark')),
                ('designation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='LGA')),
                ('lat', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone Number')),
                ('school_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='School Phone Number')),
                ('level', models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Nursery - Primary', 'Nursery - Primary'), ('Nursery - Secondary', 'Nursery - Secondary'), ('Primary - Secondary', 'Primary - Secondary'), ('Secondary School', 'Secondary School'), ('Creche/Nursery/Primary/Secondary', 'Creche/Nursery/Primary/Secondary')], max_length=100, null=True, verbose_name='Level')),
                ('target_level', models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Nursery & Primary', 'Nursery & Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary'), ('Junior & Senior Secondary', 'Junior & Senior Secondary'), ('Creche', 'Creche'), ('Kindergarten', 'Kindergarten')], max_length=100, null=True, verbose_name='Target Level')),
                ('population', models.IntegerField(blank=True, default=0, verbose_name='Total Population')),
                ('target_population', models.IntegerField(default=0, null=True, verbose_name='Target Population')),
                ('school_image', models.ImageField(blank=True, default='kelloggs/images/noimage.jpg', null=True, upload_to='kelloggs/images/', verbose_name='School Image')),
                ('feedback_form', models.ImageField(blank=True, default='kelloggs/images/noimage.jpg', null=True, upload_to='kelloggs/images/', verbose_name='Feedback Form')),
                ('mc_video', models.FileField(blank=True, null=True, upload_to='kelloggs/videos/', verbose_name='MC Video')),
                ('students_sc_img', models.ImageField(blank=True, default='kelloggs/images/noimage.jpg', null=True, upload_to='kelloggs/images/', verbose_name='Students With Cups and Sachets Image')),
                ('students_uc_img', models.ImageField(blank=True, default='kelloggs/images/noimage.jpg', null=True, upload_to='kelloggs/images/', verbose_name='Students With Uncle Coco')),
                ('date_captured', models.DateField(blank=True, null=True, verbose_name='Date Captured')),
                ('app_uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='App UID')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Kelloggs School',
            },
        ),
        migrations.CreateModel(
            name='SNTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Date Deleted')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serial Number')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Serial Numbers Trash',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='as_kids_breakfast',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Given to Kids as Breakfast'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='coco_pops_sachet_seen',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Coco Pops Sachet Seen'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='eats_coco_pops',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Consumes Kelloggs Coco Pops'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='kids_requested',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Kids Requested Coco Pos for Breakfast'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='knows_coco_pops',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Knows Kelloggs Coco Pops'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='knows_kelloggs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Knows Kelloggs'),
        ),
        migrations.AlterField(
            model_name='kelloggspostsampling',
            name='preferred_as_kids_breakfast',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Preferred as Kids Breakfast'),
        ),
        migrations.AlterField(
            model_name='kelloggspresampling',
            name='as_kids_breakfast',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Given to Kids as Breakfast'),
        ),
        migrations.AlterField(
            model_name='kelloggspresampling',
            name='coco_pops_sachet_seen',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Coco Pops Sachet Seen'),
        ),
        migrations.AlterField(
            model_name='kelloggspresampling',
            name='eats_coco_pops',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Consumes Kelloggs Coco Pops'),
        ),
        migrations.AlterField(
            model_name='kelloggspresampling',
            name='knows_coco_pops',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Knows Kelloggs Coco Pops'),
        ),
        migrations.AlterField(
            model_name='kelloggspresampling',
            name='knows_kelloggs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Knows Kelloggs'),
        ),
        migrations.AlterField(
            model_name='kelloggspresampling',
            name='preferred_as_kids_breakfast',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Preferred as Kids Breakfast'),
        ),
        migrations.AlterField(
            model_name='kelloggsretail',
            name='consumes_at_home',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Consumes Kelloggs At Home'),
        ),
        migrations.AlterField(
            model_name='kelloggsretail',
            name='kelloggs_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Kellogg Available'),
        ),
        migrations.AlterField(
            model_name='kelloggsretail',
            name='knows_coco_pops',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Do You Know Kelloggs Coco Pops'),
        ),
        migrations.AlterField(
            model_name='kelloggsretail',
            name='knows_kelloggs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=20, null=True, verbose_name='Do You Know Kelloggs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_module',
            field=models.CharField(blank=True, choices=[('School Sampling', 'School Sampling'), ('Hypo Sampling', 'Hypo Sampling'), ('University Sampling', 'University Sampling'), ('Fan Clubs', 'Fan Clubs'), ('HORECA', 'HORECA'), ('All', 'All')], max_length=200, null=True, verbose_name='User Module'),
        ),
        migrations.AddField(
            model_name='sntrash',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engage.UserProfile', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='kelloggsschool',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engage.UserProfile', verbose_name='User'),
        ),
    ]
