# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0022_auto_20190305_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelloggsschool',
            name='sampled_population',
            field=models.IntegerField(default=0, null=True, verbose_name='Sampled Population'),
        ),

    ]
