# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0024_auto_20190314_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sntrash',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Date Deleted'),
        ),
    ]
