# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0025_auto_20190314_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelloggsretail',
            name='carton_sales',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Weekly Carton Sales'),
        ),
    ]
