# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0026_auto_20190325_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True, verbose_name='Email'),
        ),
    ]
