# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0028_auto_20190512_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelloggsschool',
            name='lunch_box',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lunch Box'),
        ),
        migrations.AddField(
            model_name='kelloggsschool',
            name='lunch_box_kelloggs',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lunch Box Kelloggs'),
        ),
        migrations.AddField(
            model_name='kelloggsschool',
            name='total_population',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Population'),
        ),

    ]
