# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0029_auto_20190513_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelloggspostsampling',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engage.UserProfile', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='kelloggspresampling',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engage.UserProfile', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='kelloggsretail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engage.UserProfile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='school',
            name='population',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Population'),
        ),
    ]
