# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0031_auto_20190515_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelloggsschool',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),

    ]
