# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-02 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0032_auto_20190530_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent ID'),
        ),
        migrations.AddField(
            model_name='school',
            name='revisit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='revisited',
            field=models.BooleanField(default=False),
        ),

    ]
